GothenburgBitFactory/taskchampion-sync-server

- .github/workflows/build.yml
- .github/workflows/docker.yml
- Dockerfile
This uploads the container to the GitHub hub as a package. Tag it with either tag in tagged versions (using semver) or the branch name in the rest.
The image is created for both x64 and ARM64 (takes about 40 minutes to compile for ARM64).
With the `build.yml` pipeline it simply compile the binary and save it as an artifact. If a tag is created, it uploads the artifact to the tag as tar.xz.
> Adds Dockerfile and first version of pipelines

- .env
- .github/workflows/build.yml
- .github/workflows/docker.yml
- Dockerfile
- README.md
Instead of having to modify the environment variables separately in the pipelines (or in the Dockerfile) a `.env` file is used to declare them.
This solution adds an extra step to the pipeline but is _more open_ than using GitHub environment variables.
> Read versions from .env file

- src/storage/sqlite.rs
For example, instead of:
```
Error: Permission denied (os error 13)
```
one will get:
```
Error: Failed to create `/var/lib/taskchampion-sync-server`.
Caused by:
Permission denied (os error 13)
```
after this patch is applied.
> Provide more context on mkdir failures

- Cargo.lock
As noted in #39, the `time` crate needed to be updated in order to compile on nightly.
> time 0.3.20 -> 0.3.36

- .pre-commit-config.yaml
- src/api/add_snapshot.rs
- src/api/add_version.rs
- src/api/get_child_version.rs
- src/api/get_snapshot.rs
- src/bin/taskchampion-sync-server.rs
- src/lib.rs
- src/storage/inmemory.rs
Set up pre-commit for this repo, checking formatting and clippy.
`actix_web::test::call_service` no longer requires a mutable reference.
> Pre commit

- README.md
These don't exist, and the remainder of the README instructions are sufficient.
@ogarcia did a great job with the instructions. I don't think we need to get involved with building binaries for download.
> Remove references to release binaries

- README.md
- server/src/api/add_snapshot.rs
- server/src/api/add_version.rs
- server/src/api/get_child_version.rs
- server/src/api/get_snapshot.rs
- server/src/api/mod.rs
- server/src/bin/taskchampion-sync-server.rs
- server/src/lib.rs
This will support setting up publicly-accessible personal servers, without also allowing anyone to create a new client.
> Support a client-id allowlist

- core/src/inmemory.rs
- core/src/server.rs
- core/src/storage.rs
- server/src/api/add_snapshot.rs
- server/src/api/add_version.rs
- server/src/api/get_child_version.rs
- server/src/api/get_snapshot.rs
- sqlite/src/lib.rs
- sqlite/tests/concurrency.rs
This is a bit tricky because the `Storage` trait is `Send + Sync`, but an SQLite connection is neither. Those bounds will be useful if using `Server` from a multi-threaded web framework, so I think it's best to keep them and adapt SQLite to suit.
Since the SQLite implementation is not intended for large-scale use, the simple solution is just to open a new SQLite connection for each transaction. More complex alternatives include thread-local connection pools or a "worker thread" that owns the connection and communicates with other threads via channels.
This also updates the InMemoryStorage implementation to be a bit more strict about transactional integrity, which led to a number of test changes.
Fixes #57.
> Support sequential consistency in SQLite implementation

- core/src/inmemory.rs
- core/src/server.rs
- core/src/storage.rs
- server/src/api/add_snapshot.rs
- server/src/api/add_version.rs
- server/src/api/get_child_version.rs
- server/src/api/get_snapshot.rs
- sqlite/src/lib.rs
- sqlite/tests/concurrency.rs
Transactions for different client_ids cannot interfere with one another, so this provides an opportunity for the sort of concurrency that a mult-client hosting solution might need. For example, a postgres backend could lock the client row in each transaction.
Fixes #63.
> Make storage transactions specific to a client_id

- README.md
- docker-compose.yml
This is intended to support the user journey of someone with a VPS who wants to set up the sync server, but does not have the knowledge and skills to set up a reverse proxy and TLS certificate themselves.
A few things I'd like to add after landing this:
* #69
* #70
Fixes #53.
> Provide a docker-compose.yml that will run a server, with TLS

- core/src/inmemory.rs
- sqlite/src/lib.rs
This addresses a TODO, in a type that is really only used for testing.
This also adds a test for a similar circumstance -- adding the same version twice -- in the SQLite storage. That circumstance is already handled correctly.
> Improve error handling in the inmemory storage implementation.

- README.md
- docker-compose.yml
- server/src/bin/taskchampion-sync-server.rs
This allows to specify the listen address on the cli. I Have also changed the default to localhost because in my opinion the default should never be 0.0.0.0. But I will change it back if necessary.
I have also narrowed the data type for the port from usize to u16. This change slightly improves the error message if an out of range port number is specified
> Customize Listen Address

- README.md
- RELEASING.md
- docker-compose.yml
This makes the README refer to the latest release's `docker-compose.yml`, and makes `docker-compose.yml` refer to a versioned docker image.
Fixes #84.
> Use version-specific references for docker-compose

- Cargo.lock
- Cargo.toml
- README.md
- docker-compose.yml
- server/Cargo.toml
- server/src/bin/taskchampion-sync-server.rs
Fixes #73.
This updates the docker-compose to use the new format as well.
> Allow specifying configuration params in env vars

- .dockerignore
- Dockerfile
- docker-compose.yml
- docker-entrypoint.sh
The previous docker-compose requires end user to manually handle permissions of taskchampion data dir. And this commit has directories automatically set up in docker-entrypoint.sh, just like what postgresql did in https://github.com/docker-library/postgres/blob/master/docker-entrypoint.sh
I am not sure whether you guys like this idea, please let me know what you think.
see #87
> feat(docker): simplify docker compose for end users

- docker-entrypoint.sh
In fact, there is no taskchampion group (1092 is not a defined gid). Instead taskchampion is in the `users` group.
> Use DATA_DIR and taskchampion username in entrypoint

- README.md
- docker-compose.yml
- docker-entrypoint.sh
This also fixes up some handling of default values in the entrypoint.
Fixes #70.
> Allow specifying client ID when running docker-compose

- .github/workflows/security.yml
GH was warning about disabling this workflow because the repo has been idle.
> run the security scan weekly, not daily

- Cargo.lock
- Cargo.toml
- core/Cargo.toml
- core/src/inmemory.rs
- core/src/server.rs
- core/src/storage.rs
- server/Cargo.toml
- server/src/api/add_snapshot.rs
- server/src/api/add_version.rs
- server/src/api/get_child_version.rs
- server/src/api/get_snapshot.rs
- sqlite/Cargo.toml
- sqlite/src/lib.rs
- sqlite/tests/concurrency.rs
This will better support concurrent requests.
All of the non-test code is a straightforward transformation. The only tricky part was the tests in `core/src/server.rs`. The existing callback-based `setup` and `av_setup` functions didn't work well with async (I am not entirely sure why), so I refactored them into utility functions.
> Make Storage methods async

- .github/workflows/checks.yml
- .github/workflows/rust-tests.yml
- Cargo.lock
- Cargo.toml
- README.md
- RELEASING.md
- postgres/Cargo.toml
- postgres/README.md
- postgres/schema.sql
- postgres/src/lib.rs
- postgres/src/testing.rs
This is built to be more robust than the SQLite storage, and to integrate with other applications. The idea is that for example a web application might interact with the same DB to create and delete clients as customers come and go.
This requires rust 1.85.0 for async closures, used with `with_db` in the tests.
> Add `taskchampion-sync-server-storage-postgres`
